name: stagexl_richtextfield
version: 0.3.0+1
description: StageXL Extension for RichTextField support.
homepage: https://github.com/bp74/StageXL_RichTextField
documentation: https://github.com/bp74/StageXL_RichTextField
publish_to: none

environment:
  sdk: '^3.4.0'

dependencies:
  collection: any
  lints: ^5.1.1
  stagexl:
    git:
      url: https://github.com/mnordine/StageXL
      ref: package-web
  web: ^1.1.0

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
