name: stagexl_richtextfield
version: 0.3.0+1
authors:
- Alex Gann <k.alexgann@gmail.com>
- Bernhard Pichler <support@stagexl.org>
author:
description: StageXL Extension for RichTextField support.
homepage: https://github.com/bp74/StageXL_RichTextField
documentation: https://github.com/bp74/StageXL_RichTextField
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: any
  stagexl:
    git:
      url: https://github.com/mnordine/StageXL
      ref: dart-2-nnbd

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
